### ISSUE TITLE
Compiler specific macros

### ISSUE THREAD

**Issue by SchrodingerZhu** [chuigda/Project-CL#6]
Currently, we manually define some hint macros:
- assume
- likely/unlikely
- pure
- etc
In the future, we can leave these things to user and provide a template to it.

@ICEYSELF You can assign me for this, but let us wait until the APIs are stable.

**Comment by chuigda** [comment]
It's 3202 now. We can use properly use `cc_cfg.h` and `defs.h` to do this. If user don't provide certain macros, these macros will then have a blanket definition provided by `defs.h`. I think this should be quite correct way of doing this.
